version: '3.4'

services:
  rebussagasample.api:
    image: ${DOCKER_REGISTRY-}rebussagasampleapi
    build:
      context: RebusSagaSample.Api
      dockerfile: Dockerfile
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"